######################################################################
# Automatically generated by qmake (3.0) Mon Feb 1 09:30:07 2016
######################################################################
CONFIG += qt
CONFIG += c++11
QT += widgets testlib
TARGET = UnitTests
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include
# Input
HEADERS += testDocument.h \
           ../FishGui/document.h
SOURCES += testDocument.cpp \
            ../FishGui/document.cpp
